import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LoginButton } from "@/components/features/auth/login-button";
import { createClient } from "@/lib/supabase/server";
import { User } from "@supabase/supabase-js";
import { UserProvider } from "@/context/user";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


async function getServerUser(): Promise<User | null> {
    const supabase = await createClient();
    const { data } = await supabase.auth.getUser();
    return data ? data.user : null;
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getServerUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-white`}
      >
        <UserProvider initialUser={user}>
          <header className="w-full flex justify-end p-4">
            <LoginButton />
          </header>

          <main>{children}</main>
        </UserProvider>
        
      </body>
    </html>
  );
}
